add_newline = false
format = '▲ ($username@$hostname) $directory($git_branch@$git_commit)($git_status )'

[username]
format = '[$user]($style)'
show_always = true
style_user = 'white'

[hostname]
ssh_only = false
format = '[$hostname](white)'

[directory]
style = 'bold white'
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[$branch]($style)'
style = 'bold green'

[git_commit]
commit_hash_length = 8
disabled = false
format = '[$hash]($style) '
only_detached = false
style = 'bold yellow'

[git_status]
ahead = "↑"
behind = "↓"
conflicted = "​"
deleted = "​"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind$stashed)]($style)"
modified = "​"
renamed = "​"
staged = "​"
stashed = "≡"
style = "red"
untracked = "​"
