theme = "vesper"

[editor]
auto-save = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
line-number = "relative"
true-color = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.lsp]
display-inlay-hints = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
center = ["spinner"]
left = ["mode", "file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
