[[language]]
auto-format = true
comment-token = "#"
file-types = ["py"]
indent = {tab-width = 4, unit = "    "}
injection-regex = "python"
language-server = {command = "pylsp"}
name = "python"
roots = []
scope = "source.python"
shebangs = ["python"]
[language.formatter]
args = [
  "-", # stdin
  "--quiet",
  "--line-length=79",
]
command = "black"
