[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "pyright", except-features = [
    "format",
    "diagnostics",
  ] },
  { name = "ruff", only-features = [
    "format",
    "diagnostics",
  ] },
]

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "sql"
auto-format = true
formatter = { command = "sqlfluff", args = [
  "fix",
  "--exclude-rules",
  "ST06",
  "--dialect",
  "postgres",
  "-",
] }
