[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "sql"
auto-format = true
formatter = { command = "sqlfluff", args = [
  "fix",
  "--exclude-rules",
  "ST06",
  "--dialect",
  "postgres",
  "-",
] }
