[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
auto-format = true

[language-server.ruff.config.settings]
lineLength = 120

[[language]]
name = "sql"
auto-format = true
formatter = { command = "sqlfluff", args = [
  "format",
  "--nocolor",
  "--config",
  "/Users/carlos/.sqlfluff",
  "-",
] }
