[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "ComicShannsMono Nerd Font"
size = 14

[general]
import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]
